# Generated by Django 5.1 on 2025-03-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_achievements_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
