# Generated by Django 5.1 on 2025-03-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_achievements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
            preserve_default=False,
        ),
    ]
