# Generated by Django 5.1 on 2025-03-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_faq_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
    ]
