# Generated by Django 5.1 on 2025-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
