# Generated by Django 5.1 on 2025-03-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_achievements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
