# Generated by Django 5.1 on 2025-03-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_achievements_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='profile',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
    ]
